version: "3.8"

services:
  backend:
    build: ./trilha-Api-TIVIT
    container_name: tarefas-backend
    ports:
      - "8001:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DockerConnection=Server=tarefas-db,1433;Database=TarefasDb;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;
      - TokenConfigurations__Audience=tarefas-api
      - TokenConfigurations__Issuer=tarefas-api
      - TokenConfigurations__Secret=chave-super-secreta-para-jwt-123456
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tarefas-network

  frontend:
    build: ./trilha-react-TIVIT
    container_name: tarefas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tarefas-network

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: tarefas-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123!
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "SenhaForte123!",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tarefas-network

volumes:
  sql_data:

networks:
  tarefas-network:
