version: "3.8"
services:
  backend:
    build: ./trilha-Api-TIVIT
    container_name: tarefas-backend
    ports:
      - "8001:8080" # bate com EXPOSE do Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__LocalConnection=Server=db;Database=TarefasDB;User Id=SA;Password=SenhaForte123!;Encrypt=False;
    depends_on:
      - db
    networks:
      - tarefas-network

  frontend:
    build:
      context: ./trilha-react-TIVIT
      dockerfile: Dockerfile
    container_name: tarefas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tarefas-network

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: tarefas-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte123!
    ports:
      - "14330:1433"
    networks:
      - tarefas-network

networks:
  tarefas-network:
